apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kpt-examples
  annotations:
    kubernetes.io/description: >
      Example using public KPT functions. 
      refs: 
      - image repo: https://console.cloud.google.com/gcr/images/kpt-fn
namespace: default
resources:
- resource.yaml
transformers:
- replace.yaml
