apiVersion: v1
kind: ConfigMap
metadata:
  name: replace-fn-config
  annotations:
    config.kubernetes.io/function: |
      container:
        image: gcr.io/kpt-fn/search-replace:unstable
data:
  by-path: spec.image
  put-value: nginx:schmoo